# Use the golang image as both the builder and runtime environment
FROM golang:1.23.3-alpine3.20 as builder

RUN apk add --no-cache curl wget

WORKDIR /usr/src/app
COPY . .

RUN go mod tidy
RUN go mod vendor

# Build the pocketbase binary
RUN go build -o /usr/local/bin/pocketbase

# Define the command to run pocketbase
CMD ["/usr/local/bin/pocketbase", "serve", "--http=0.0.0.0:8090"]
