FROM golang:1.23.3-alpine3.20 as base
RUN apk add --no-cache curl wget

WORKDIR /usr/src/app
COPY . .

RUN go mod tidy
RUN go mod vendor

RUN chmod +x /usr/src/app/docker/scripts/prod.sh
VOLUME /usr/src/app/vendor

CMD ["/bin/sh", "/usr/src/app/docker/scripts/prod.sh"]